### PR TITLE
Fix/sphere water interaction range

### PR DESCRIPTION
**Pull request by huwb**
Thanks for the feedback on #778 . You were right, it LOD'd far too aggressively. Inspecting carefully i think the range could be extended a ton, it should be similar to before now.

### CODE REVIEW

**Comment by daleeidd** [comment]
That fixes it at a distance. I did some more comparisons and I found that they are more powerful than the old approach before fixed time. The following images is at around 10 seconds elapsed game time.

**Before fixed time steps**
111 1 Old

**This PR**
111 2 PR

**After changing both 0.2s to 0.1s in shader**
111 3 PR Adjusted

Not sure if this was intentional. I found comparing the data textures themselves to be difficult since the pattern is a little different.

**Review by daleeidd — APPROVED** [review]
Looks good :^)

**Comment by huwb** [comment]
Ah thanks. I did make it a bit stronger. However I will recheck and try 0.1 and may push an update later. For now I'll merge this as a range fix.

**Comment by huwb** [comment]
0.1 seems far too chill in terms of displacement/shape when im close up to the spinner. but i appreciate the difference above is significant - at least in terms of foam? im not quite sure but i think ill leave it as is.

**Comment by daleeidd** [comment]
Yeah, it's probably just the foam. My bad.

Happy to leave it. Thought I'd mention it though.

**Comment by huwb** [comment]
Yes was a useful callout, and may be useful to refer back to later

**Pull request merged**
