### PR TITLE
Overhaul of wave conditions section

### PR DESCRIPTION
**Pull request by huwb**
Brutal rewrite. More general user focused rather than coder focused. Lots of legacy stuff torn out.

### CODE REVIEW

**Comment by huwb** [comment]
I've generalised this slightly to add TPs too but i've run out of time to generalise this PR and make sure it all works, and it may need a polish pass. If you could let me know what you think and feel free to make any tweaks that would be great.

**Comment by daleeidd** [comment]
I hope you don't mind, but I added some commits to add some luxuries and polish. I made this branch active:

https://crest.readthedocs.io/en/feature-rewrite-wave-conditions/

**Review by daleeidd — APPROVED** [review]
Good rewrite. At some point that video you made of comparing Gerstners and FFTs would make a great YT embed in this section.

**Comment by huwb** [comment]
thanks! agreed about that vid. i will merge this, and then do another pass soon. thanks for helping polish this up!

**Pull request merged**
