### PR TITLE
Fix white texture when sims are disabled with texture quality below full resolution (workaround)

### PR DESCRIPTION
**Pull request by daleeidd**
When "Project Settings > Texture Quality" is not "Full Res" our black texture array becomes white (probably junk). This is a bug with _Graphics.CopyTexture_ when using texture arrays. This can happen in builds when quality settings may be different (ie high in editor or low in build) than in editor which can be hard to debug.

Workaround is to set [_QualitySettings.masterTextureLimit_](https://docs.unity3d.com/ScriptReference/QualitySettings-masterTextureLimit.html) to zero before calling _Graphics.CopyTexture_. I have seen others do this for other bugs for this same method. We can also use SetPixels instead but this looks good enough. I have submitted a bug report to Unity for texture arrays.

### CODE REVIEW

**Comment by huwb** [comment]
Wow thats quite a workaround! Hope that does not cause a hitch at runtime.

Is there a bug number around for this, out of interest?

It occurs to me that an alternative could be to do the copy in one compute dispatch. Not 100% sure if it would work but seemed worth mentioning.

If thats what others are doing then thumbs up. Not sure if it needs a release note but approving anyway.

**Review by huwb — APPROVED** [review]

**Comment by huwb** [comment]
(Total aside but it took me a while to figure out/remember what this function does. Is it creating a 'null' texture array to use when sims are disabled? And the copy is there because the input texture array gives the default 'null colour'? I think we could probably clarify the naming a lot as it sells itself as creating a clone of a texture array. Happy to propose something in a separate commit.)

**Comment by daleeidd** [comment]
> Hope that does not cause a hitch at runtime.

I didn't notice anything. I tested it by running it every frame. But after reading it again, maybe it is a little dangerous. Fear is with a project with a lot of textures, it would load up all full resolution textures.

> Is there a bug number around for this, out of interest?

There wasn't. But there is now. I've added it as a comment.
https://issuetracker.unity3d.com/product/unity/issues/guid/1365775

> It occurs to me that an alternative could be to do the copy in one compute dispatch. Not 100% sure if it would work but seemed worth mentioning.

Like clear to black?

**Comment by daleeidd** [comment]
I went with SetPixels as is safer than last approach and simple change. Works in editor and build from testing.

> (Total aside but it took me a while to figure out/remember what this function does. Is it creating a 'null' texture array to use when sims are disabled? And the copy is there because the input texture array gives the default 'null colour'? I think we could probably clarify the naming a lot as it sells itself as creating a clone of a texture array. Happy to propose something in a separate commit.)

Correct. Sure. Sounds good.

**Comment by huwb** [comment]
Ah cool thanks for going the extra mile there, feel better about that

**Comment by daleeidd** [comment]
Thank you.

**Pull request merged**
