### PR TITLE
Use InputSystem when enabled in build settings

### PR DESCRIPTION
**Pull request by sagron**
Can probably be cleaned up more using variables, but for now a straight drop-in replacement around input code that shouldn't impact existing functionality.

### CODE REVIEW

**Review by daleeidd — CHANGES_REQUESTED** [review]
Thanks. All of it looks great. You're just missing a couple of files to make this complete:
- _Crest/Crest/Scripts/Interaction/BoatProbes.cs_
- _Development/Scripts/TestCameraChange.cs_
  - When you add the input reference to the Development asmdef, uncheck "use GUID" and ignore the GUID that is already there

**Comment by daleeidd** [comment]
@huwb I think I will just merge this in and finish the rest in master. Is this okay?

**Comment by huwb** [comment]
Sure

**Comment by daleeidd** [comment]
Thanks. And thanks @sagron for the PR.

**Pull request merged**
