### PR TITLE
Clip surface input inverted option

### PR DESCRIPTION
**Pull request by daleeidd**
Adds an "inverted" option to both SDF and convex hull clip surface inputs. Both of these can now remove clip surface data.

With the new order property for SDF, one can create some interesting patterns:

SDFCH
Left: Convex Hull. Right: SDFs

### CODE REVIEW

**Comment by huwb** [comment]
Ha thats awesome

**Review by huwb — APPROVED** [review]
Ah interesting that the order needs to be exposed. Nice one

**Comment by daleeidd** [comment]
> Ah interesting that the order needs to be exposed. Nice one

Before we got the order from the shader/material render queue. But we don't expose them for SDFs.

**Comment by huwb** [comment]
Yeah cool

**Pull request merged**
