### PR TITLE
Report renderer bounds by default for Animated Waves input

### PR DESCRIPTION
**Pull request by daleeidd**
Helps solve #865

Reports the renderer bounds on Animated Waves input by default. The reasoning is that I think reporting the renderer bounds requires some understanding of the system which most will not know. They may come across this issue and not understand the cause. This is a "working correctly by default and optimisation yourself" approach. Let me know what you think.

### CODE REVIEW

**Review by huwb — CHANGES_REQUESTED** [review]
Yeah works for me, but if we want it to work by default then we need to set the numbers reported to something non zero.

We could set _maxDisplacementVertical to 2m and maybe the horizontal one to 1m?

**Comment by daleeidd** [comment]
Good point. I thought it worked just by toggle that property but it looks like it only really works for the vertical:

```csharp
// let ocean system know how far from the sea level this shape may displace the surface
if (_reportRendererBoundsToOceanSystem && _renderer != null)
{
    var minY = _renderer.bounds.min.y;
    var maxY = _renderer.bounds.max.y;
    var seaLevel = OceanRenderer.Instance.SeaLevel;
    maxDispVert = Mathf.Max(maxDispVert, Mathf.Abs(seaLevel - minY), Mathf.Abs(seaLevel - maxY));
}
```

Should we only do this for the height input? Then the toggle will be enough. Although we could just remove both settings since it looks solid enough to just do regardless for the height input.

**Review by huwb — APPROVED** [review]

**Comment by huwb** [comment]
It's worth noting that this will push up the sea level to where the height input is, but any waves beyond that won't be accounted for. But the fix for that would be a strong notion of sea level which is the last pr for local water bodies. This is still worth merging anyway.

**Comment by daleeidd** [comment]
Thank you

**Pull request merged**
