### PR TITLE
Add Crest icon to components and SOs under Crest/Scripts

### PR DESCRIPTION
**Pull request by daleeidd**
Adds the Crest icon to all MonoBehaviour and ScriptableObject classes which are located under Crest/Scripts.

We can go even further one day and add custom icons tailored to each component.

### CODE REVIEW

**Comment by huwb** [comment]
Looks good. Is the crest icon image in the assets folder already?

**Review by huwb — APPROVED** [review]

**Comment by daleeidd** [comment]
> Is the crest icon image in the assets folder already?

It is... but in Crest-Examples. I'll have to promote it to Crest.

**Comment by daleeidd** [comment]
I've moved it into a new Crest/Icons folder.

**Comment by huwb** [comment]
Sweet

**Comment by huwb** [comment]
I've ran into an issue unfortunately - the icons are used as gizmos in the scene view so all the crest components seem to have representation in the scene view now. 

image

Maybe to some extent this is ok, but the spline points either need a different icon, or they want to have no icon so that they use the gizmoe we use now. And some other components we may not want to have icons drawn for because their 3d position is not interesting to see, nor is having a quick way to select them useful i dont think.. but let me know what you think.

I'm not sure if the gizmo icon can be disabled for some things, that could be useful.

**Comment by huwb** [comment]
(Having icons on our scriptable objects / settings assets works well though)

**Comment by daleeidd** [comment]
I found a way using reflection. Will do a PR for it tomorrow.

**Pull request merged**
