### PR TITLE
Fix FFTs not updating with spectrum changes when paused

### PR DESCRIPTION
**Pull request by daleeidd**
This is just a quick fix. Downside is that it runs at full rate instead of editor update intervals. Alternatives could be to add a CurrentUnscaledTime similar to CurrentTime. Or to hash the spectrum.

Let me know what you think.

### CODE REVIEW

**Comment by huwb** [comment]
There's an updateSpectrum argument that is intended to support this. Maybe it broke somewhere along the way. The intention is that you can set that argument to true and it will force a generate.

**Comment by daleeidd** [comment]
I totally missed that. That does work. Thanks.

**Review by huwb — APPROVED** [review]
Thanks great fix

**Comment by daleeidd** [comment]
Thanks.

**Pull request merged**
