### PR TITLE
Add query gizmos to BoatProbes

### PR DESCRIPTION
**Pull request by daleeidd**
Just some basic ones similar to BoatAlignNormal.

### CODE REVIEW

**Comment by huwb** [comment]
That's cool. Interesting pattern with the debug, is that a way to get collapsible? I wonder if "Debug" should still be bold if possible? Guess it doesn't matter too much.

Perhaps it should be a struct instead of a class, for garbage reasons? If it still works that way.

Does it retain its expanded/collapsed state Street changing selection? I'm not sure but I think going to and from different GOs and toggling debug on/off might be common.

Sorry to fixate on details, I'm keen on the pattern so just checking.

**Review by huwb — COMMENTED** [review]
Added Q's

**Comment by huwb** [comment]
> Does it retain its expanded/collapsed state

Side note, It occurs to me that embedded SOs retain this state, not sure if there is specific code to support this.

**Comment by daleeidd** [comment]
> That's cool. Interesting pattern with the debug, is that a way to get collapsible?

It is. Also a nice way to segregate debug properties.

> I wonder if "Debug" should still be bold if possible? Guess it doesn't matter too much.

I don't think I can. It's not too big of a deal in this case as it keeps debug low-key.

> Perhaps it should be a struct instead of a class, for garbage reasons? If it still works that way.

Not a bad idea. If going with a struct we cannot use initialisers so we have to do default values this way:

```csharp
DebugFields _debug = new DebugFields()
{
    _drawQueries = false,
};

[Serializable]
struct DebugFields
{
    [Tooltip("Draw queries for each force point as gizmos.")]
    public bool _drawQueries;
}
```

LMKWYT.

> Does it retain its expanded/collapsed state after changing selection? I'm not sure but I think going to and from different GOs and toggling debug on/off might be common so retaining this would be ideal.

It does.

**Comment by huwb** [comment]
Thanks that all makes sense. Let's keep it how you have it. Nice one.

**Review by huwb — APPROVED** [review]

**Comment by daleeidd** [comment]
Thanks!

**Comment by sardinxp** [comment]
> Thanks that all makes sense. Let's keep it how you have it. Nice one.

Hi huwb

I've been trying for almost 2 weeks to add a function in boatprobes.cs so that the boat can be controlled using 3d XRWheel and XRLever but failed for my VR project. I use the VR interaction tool kit as the VR engine.

Below is the boatprobes script that has been modified to integrate XRWheel and XRLever:

// Crest Ocean System
// Copyright 2020 Wave Harmonic Ltd
// Shout out to @holdingjason who posted a first version of this script here: https://github.com/huwb/crest-oceanrender/pull/100
#if CREST_UNITY_INPUT && ENABLE_INPUT_SYSTEM
#define INPUT_SYSTEM_ENABLED
#endif

using UnityEngine;
using UnityEngine.Serialization;
using UnityEngine.XR;
using UnityEngine.XR.Interaction.Toolkit;

namespace Crest
{
    [AddComponentMenu(Internal.Constants.MENU_PREFIX_SCRIPTS + "Boat Probes")]
    public class BoatProbes : FloatingObjectBase
    {
        [SerializeField, HideInInspector]
        int _version = 0;

        [Header("Forces")]
        [Tooltip("Override RB center of mass, in local space."), SerializeField]
        Vector3 _centerOfMass = Vector3.zero;
        [SerializeField, FormerlySerializedAs("ForcePoints")]
        FloaterForcePoints[] _forcePoints = new FloaterForcePoints[] { };
        [Tooltip("Vertical offset for where engine force should be applied.")]
        public float _forceHeightOffset = 0f;
        public float _forceMultiplier = 10f;
        [Tooltip("Width dimension of boat. The larger this value, the more filtered/smooth the wave response will be.")]
        public float _minSpatialLength = 12f;
        [Range(0, 1)]
        public float _turningHeel = 0.35f;
        [Tooltip("Clamps the buoyancy force to this value. Useful for handling fully submerged objects. Enter 'Infinity' to disable.")]
        public float _maximumBuoyancyForce = Mathf.Infinity;

        [Header("Drag")]
        public float _dragInWaterUp = 3f;
        public float _dragInWaterRight = 2f;
        public float _dragInWaterForward = 1f;

        [Header("Control")]
        public float _enginePower = 7;
        public float _turnPower = 0.5f;
        public bool _playerControlled = true;
        public float _engineBias = 0f;
        public float _turnBias = 0f;

        // Debug
        [Space(10)]

        [SerializeField]
        DebugFields _debug = new DebugFields();

        [System.Serializable]
        class DebugFields
        {
            [Tooltip("Draw queries for each force point as gizmos.")]
            public bool _drawQueries = false;
        }

        private const float WATER_DENSITY = 1000;

        public override Vector3 Velocity => _rb.velocity;

        Rigidbody _rb;

        public override float ObjectWidth => _minSpatialLength;
        public override bool InWater => true;

        float _totalWeight;

        Vector3[] _queryPoints;
        Vector3[] _queryResultDisps;
        Vector3[] _queryResultVels;

        SampleFlowHelper _sampleFlowHelper = new SampleFlowHelper();

        [Header("XR Steering Wheel")]
        [SerializeField]
        XRSteeringWheel _steeringWheel;

        private void Awake()
        {
            _rb = GetComponent<Rigidbody>();
            _rb.centerOfMass = _centerOfMass;

            if (OceanRenderer.Instance == null)
            {
                enabled = false;
                return;
            }

            CalcTotalWeight();

            _queryPoints = new Vector3[_forcePoints.Length + 1];
            _queryResultDisps = new Vector3[_forcePoints.Length + 1];
            _queryResultVels = new Vector3[_forcePoints.Length + 1];
        }

        void CalcTotalWeight()
        {
            _totalWeight = 0f;
            foreach (var pt in _forcePoints)
            {
                _totalWeight += pt._weight;
            }
        }

        private void FixedUpdate()
        {
#if UNITY_EDITOR
            // Sum weights every frame when running in the editor in case weights are edited in the inspector.
            CalcTotalWeight();
#endif

            if (OceanRenderer.Instance == null)
            {
                return;
            }

            var collProvider = OceanRenderer.Instance.CollisionProvider;

            // Do queries
            UpdateWaterQueries(collProvider);

            var undispPos = transform.position - _queryResultDisps[_forcePoints.Length];
            undispPos.y = OceanRenderer.Instance.SeaLevel;

            var waterSurfaceVel = _queryResultVels[_forcePoints.Length];

            {
                _sampleFlowHelper.Init(transform.position, _minSpatialLength);
                _sampleFlowHelper.Sample(out var surfaceFlow);
                waterSurfaceVel += new Vector3(surfaceFlow.x, 0, surfaceFlow.y);
            }

            if (_debug._drawQueries)
            {
                Debug.DrawLine(transform.position + 5f * Vector3.up, transform.position + 5f * Vector3.up +
                    waterSurfaceVel, new Color(1, 1, 1, 0.6f));
            }

            // Buoyancy
            FixedUpdateBuoyancy();
            FixedUpdateDrag(waterSurfaceVel);
            FixedUpdateEngine();
        }

        void UpdateWaterQueries(ICollProvider collProvider)
        {
            // Update query points
            for (int i = 0; i < _forcePoints.Length; i++)
            {
                _queryPoints[i] = transform.TransformPoint(_forcePoints[i]._offsetPosition + new Vector3(0, _centerOfMass.y, 0));
            }
            _queryPoints[_forcePoints.Length] = transform.position;

            collProvider.Query(GetHashCode(), ObjectWidth, _queryPoints, _queryResultDisps, null, _queryResultVels);

            if (_debug._drawQueries)
            {
                for (var i = 0; i < _forcePoints.Length; i++)
                {
                    var query = _queryPoints[i];
                    query.y = OceanRenderer.Instance.SeaLevel + _queryResultDisps[i].y;
                    VisualiseCollisionArea.DebugDrawCross(query, 1f, Color.magenta);
                }
            }
        }

        void FixedUpdateEngine()
        {
            var forcePosition = _rb.position;

            var forward = _engineBias;
            if (_playerControlled) forward +=
#if INPUT_SYSTEM_ENABLED
                !Application.isFocused ? 0 :
                ((Keyboard.current.wKey.isPressed ? 1 : 0) + (Keyboard.current.sKey.isPressed ? -1 : 0));
#else
                Input.GetAxis("Vertical");
#endif
            _rb.AddForceAtPosition(_enginePower * forward * transform.forward, forcePosition, ForceMode.Acceleration);

            var sideways = _turnBias;
            if (_playerControlled) sideways +=
#if INPUT_SYSTEM_ENABLED
                !Application.isFocused ? 0 :
                ((Keyboard.current.aKey.isPressed ? -1f : 0f) +
                (Keyboard.current.dKey.isPressed ? 1f : 0f));
#else
                (Input.GetKey(KeyCode.A) ? -1f : 0f) +
                (Input.GetKey(KeyCode.D) ? 1f : 0f);
#endif
            var rotVec = transform.up + _turningHeel * transform.forward;
            _rb.AddTorque(_turnPower * sideways * rotVec, ForceMode.Acceleration);

            // XR Steering Wheel integration
            if (_steeringWheel != null)
            {
                // Get the rotation value from the XR Steering Wheel
                var rotationValue = _steeringWheel.value;

                // Apply rotation force based on the XR Steering Wheel input
                _rb.AddTorque(transform.up * _turnPower * rotationValue, ForceMode.Acceleration);
            }
        }

        void FixedUpdateBuoyancy()
        {
            var archimedesForceMagnitude = WATER_DENSITY * Mathf.Abs(Physics.gravity.y);

            for (int i = 0; i < _forcePoints.Length; i++)
            {
                var waterHeight = OceanRenderer.Instance.SeaLevel + _queryResultDisps[i].y;
                var heightDiff = waterHeight - _queryPoints[i].y;
                if (heightDiff > 0)
                {
                    var force = _forceMultiplier * _forcePoints[i]._weight * archimedesForceMagnitude * heightDiff * Vector3.up / _totalWeight;
                    if (_maximumBuoyancyForce < Mathf.Infinity)
                    {
                        force = Vector3.ClampMagnitude(force, _maximumBuoyancyForce);
                    }
                    _rb.AddForceAtPosition(force, _queryPoints[i]);
                }
            }
        }

        void FixedUpdateDrag(Vector3 waterSurfaceVel)
        {
            // Apply drag relative to water
            var _velocityRelativeToWater = _rb.velocity - waterSurfaceVel;

            var forcePosition = _rb.position + _forceHeightOffset * Vector3.up;
            _rb.AddForceAtPosition(_dragInWaterUp * Vector3.Dot(Vector3.up, -_velocityRelativeToWater) * Vector3.up, forcePosition, ForceMode.Acceleration);
            _rb.AddForceAtPosition(_dragInWaterRight * Vector3.Dot(transform.right, -_velocityRelativeToWater) * transform.right, forcePosition, ForceMode.Acceleration);
            _rb.AddForceAtPosition(_dragInWaterForward * Vector3.Dot(transform.forward, -_velocityRelativeToWater) * transform.forward, forcePosition, ForceMode.Acceleration);
        }

        private void OnDrawGizmosSelected()
        {
            Gizmos.color = Color.yellow;
            Gizmos.DrawCube(transform.TransformPoint(_centerOfMass), Vector3.one * 0.25f);

            for (int i = 0; i < _forcePoints.Length; i++)
            {
                var point = _forcePoints[i];

                var transformedPoint = transform.TransformPoint(point._offsetPosition + new Vector3(0, _centerOfMass.y, 0));

                Gizmos.color = Color.red;
                Gizmos.DrawCube(transformedPoint, Vector3.one * 0.5f);
            }
        }
    }

    [System.Serializable]
    public class FloaterForcePoints
    {
        public float _weight = 1f;
        public Vector3 _offsetPosition;
    }
}

**Comment by sardinxp** [comment]
> Thanks that all makes sense. Let's keep it how you have it. Nice one.

Hi huwb. I'm new in C# programming. I've been trying for almost 2 weeks to add a function in boatprobes.cs so that the boat can be controlled using 3d XRWheel and XRLever but failed for my VR project. I use the VR interaction tool kit as the VR engine.

**Comment by sardinxp** [comment]
Below is the error displayed on the console when I make changes to the boatprobes.cs script:

Assets\Crest\Crest\Scripts\Interaction\BoatProbes.cs(11,22): error CS0234: The type or namespace name 'Interaction' does not exist in the namespace 'UnityEngine.XR' (are you missing an assembly reference?)

Assets\Crest\Crest\Scripts\Interaction\BoatProbes.cs(80,9): error CS0246: The type or namespace name 'XRSteeringWheel' could not be found (are you missing a using directive or an assembly reference?)

**Comment by sardinxp** [comment]
attached the modified BoatProbes.cs file:
[BoatProbes (2).zip](https://github.com/wave-harmonic/crest/files/13442753/BoatProbes.2.zip)

**Pull request merged**
