### PR TITLE
Ramp planar reflection distortion with pixel Z

### PR DESCRIPTION
**Pull request by huwb**
Not ready to be merged - experimental for now.

### CODE REVIEW

**Comment by huwb** [comment]
Closing for lack of feedback. We can revive this if it comes up again.

**Comment by huwb** [comment]
@Winux1062 tested this and said it works well, so reopening for reconsideration

**Comment by daleeidd** [comment]
@huwb I brought this one up-to-date as someone asked for it. I think all it needs is a range property to scale this distortion multiplier to give users control. Thoughts?

**Comment by huwb** [comment]
Yeah I guess so. I suppose this is birp only?

**Comment by daleeidd** [comment]
Also URP until SG swap.

**Comment by daleeidd** [comment]
All done. I didn't add another multiplier we already have one.

**Review by huwb — COMMENTED** [review]
Thanks. So this should work for existing cases and not break anything for existing users? Just checking.

**Comment by huwb** [comment]
I tried to approve but it didn't let me. That's a new one. Consider it approved..

**Comment by daleeidd** [comment]
> Thanks. So this should work for existing cases and not break anything for existing users? Just checking.

It will be different. I could add it to "breaking"? Or we could hold off until 5.0.

**Pull request merged**
